// <auto-generated />
using System;
using GheyomAlwadaqTask.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GheyomAlwadaqTask.DAL.Data.Migrations
{
    [DbContext(typeof(GheyomAlwadaqContext))]
    partial class GheyomAlwadaqContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Default_Slice_Values", b =>
                {
                    b.Property<string>("NWC_Default_Slice_Values_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)");

                    b.Property<int>("NWC_Default_Slice_Values_Condtion")
                        .HasColumnType("int");

                    b.Property<string>("NWC_Default_Slice_Values_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NWC_Default_Slice_Values_Reasons")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NWC_Default_Slice_Values_Sanitation_Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("NWC_Default_Slice_Values_Water_Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("NWC_Default_Slice_Values_Code");

                    b.ToTable("NWC_Default_Slice_Values");
                });

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Invoices", b =>
                {
                    b.Property<string>("NWC_Invoices_No")
                        .HasColumnType("char(10)");

                    b.Property<int>("NWC_Invoices_Amount_Consumption")
                        .HasColumnType("int");

                    b.Property<decimal>("NWC_Invoices_Consumption_Value")
                        .HasColumnType("dec(10,2)");

                    b.Property<int>("NWC_Invoices_Current_Consumption_Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("NWC_Invoices_Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("NWC_Invoices_From")
                        .HasColumnType("date");

                    b.Property<string>("NWC_Invoices_Is_There_Sanitation")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<int>("NWC_Invoices_Previous_Consumption_Amount")
                        .HasColumnType("int");

                    b.Property<string>("NWC_Invoices_Rreal_Estate_Types")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<decimal>("NWC_Invoices_Service_Fee")
                        .HasColumnType("dec(10,2)");

                    b.Property<string>("NWC_Invoices_Subscriber_No")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<string>("NWC_Invoices_Subscription_No")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<decimal>("NWC_Invoices_Tax_Rate")
                        .HasColumnType("dec(10,2)");

                    b.Property<decimal>("NWC_Invoices_Tax_Value")
                        .HasColumnType("dec(10,2)");

                    b.Property<DateTime>("NWC_Invoices_To")
                        .HasColumnType("date");

                    b.Property<decimal>("NWC_Invoices_Total_Bill")
                        .HasColumnType("dec(10,2)");

                    b.Property<decimal>("NWC_Invoices_Total_Invoice")
                        .HasColumnType("dec(10,2)");

                    b.Property<string>("NWC_Invoices_Total_Reasons")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("NWC_Invoices_Wastewater_Consumption_Value")
                        .HasColumnType("dec(10,2)");

                    b.Property<string>("NWC_Invoices_Year")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.HasKey("NWC_Invoices_No");

                    b.HasIndex("NWC_Invoices_Rreal_Estate_Types");

                    b.HasIndex("NWC_Invoices_Subscriber_No");

                    b.HasIndex("NWC_Invoices_Subscription_No");

                    b.ToTable("NWC_Invoices");
                });

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Rreal_Estate_Types", b =>
                {
                    b.Property<string>("NWC_Rreal_Estate_Types_Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)");

                    b.Property<string>("NWC_Rreal_Estate_Types_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NWC_Rreal_Estate_Types_Reasons")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NWC_Rreal_Estate_Types_Code");

                    b.ToTable("NWC_Rreal_Estate_Types");
                });

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Subscriber_File", b =>
                {
                    b.Property<string>("NWC_Subscriber_File_Id")
                        .HasColumnType("char(10)");

                    b.Property<string>("NWC_Subscriber_File_Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NWC_Subscriber_File_City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NWC_Subscriber_File_Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NWC_Subscriber_File_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NWC_Subscriber_File_Reasons")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NWC_Subscriber_File_Id");

                    b.ToTable("NWC_Subscriber_File");
                });

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Subscription_File", b =>
                {
                    b.Property<string>("NWC_Subscription_File_No")
                        .HasColumnType("char(10)");

                    b.Property<bool>("NWC_Subscription_File_Is_There_Sanitation")
                        .HasColumnType("bit");

                    b.Property<int>("NWC_Subscription_File_Last_Reading_Meter")
                        .HasColumnType("int");

                    b.Property<string>("NWC_Subscription_File_Reasons")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NWC_Subscription_File_Rreal_Estate_Types_Code")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("NWC_Subscription_File_Subscriber_Code")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<int>("NWC_Subscription_File_Unit_No")
                        .HasColumnType("int");

                    b.HasKey("NWC_Subscription_File_No");

                    b.HasIndex("NWC_Subscription_File_Rreal_Estate_Types_Code");

                    b.HasIndex("NWC_Subscription_File_Subscriber_Code");

                    b.ToTable("NWC_Subscription_File");
                });

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Invoices", b =>
                {
                    b.HasOne("GheyomAlwadaqTask.DAL.Entities.NWC_Rreal_Estate_Types", "NWC_Rreal_Estate_Types")
                        .WithMany()
                        .HasForeignKey("NWC_Invoices_Rreal_Estate_Types")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GheyomAlwadaqTask.DAL.Entities.NWC_Subscriber_File", "NWC_Subscriber_File")
                        .WithMany()
                        .HasForeignKey("NWC_Invoices_Subscriber_No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GheyomAlwadaqTask.DAL.Entities.NWC_Subscription_File", "NWC_Subscription_File")
                        .WithMany()
                        .HasForeignKey("NWC_Invoices_Subscription_No")
                        .IsRequired();

                    b.Navigation("NWC_Rreal_Estate_Types");

                    b.Navigation("NWC_Subscriber_File");

                    b.Navigation("NWC_Subscription_File");
                });

            modelBuilder.Entity("GheyomAlwadaqTask.DAL.Entities.NWC_Subscription_File", b =>
                {
                    b.HasOne("GheyomAlwadaqTask.DAL.Entities.NWC_Rreal_Estate_Types", "NWC_Rreal_Estate_Types")
                        .WithMany()
                        .HasForeignKey("NWC_Subscription_File_Rreal_Estate_Types_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GheyomAlwadaqTask.DAL.Entities.NWC_Subscriber_File", "NWC_Subscriber_File")
                        .WithMany()
                        .HasForeignKey("NWC_Subscription_File_Subscriber_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NWC_Rreal_Estate_Types");

                    b.Navigation("NWC_Subscriber_File");
                });
#pragma warning restore 612, 618
        }
    }
}
